version : '3.8'

services:
  postgres:
    image: postgres:12 #hub.docker.com
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    
  redis:
    imgae: redis:6.0.9
    ports:
      - "6379:6379"
    